### ISSUE TITLE
Archive results for benchmarking search individuals/biosamples 

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics#102]
@arko-bhattacharya 

A few more requests on this:

1. Can you paste in the corresponding graphs for downloading biosamples (using Kb as the unit size)?
2. Can you rerun the script with download for individuals (using `search_individuals` instead of `search_biosamples`). In the script, also turn off expression download (maybe put in some NA results as placeholders) so that the `get_time...` script runs faster.

_Originally posted by @ksens in https://github.com/Paradigm4/revealgenomics/issues/92#issuecomment-521616874_

**Comment by arko-bhattacharya** [comment]
Uploaded graphs with biosample size in Kb in #108.

**Comment by ksens** [comment]
@arko-bhattacharya 

This should be sufficient for now. I am thinking of another strategy for benchmarking the timing for `search_individuals` -- but this is lower priority, and we can take it up later. 

For reference, the results are archived at #108 and https://github.com/Paradigm4/revealgenomics/wiki/Benchmark-results

**Comment by arko-bhattacharya** [comment]
Here is a performance benchmarking plot for search_individuals(). 'master' in this plot refers to the current master with optimizations for continuous and discontinuous dense matrices. 'master_legacy' refers to the master branch before any optimizations were in place i.e it is the master before PR merge for 'dt_enhancements_v2' were in place.

![runTime-20190907-search_individuals-myOptim-vs-masterBeforeDtEncV2](https://user-images.githubusercontent.com/16749721/64469515-136d5800-d151-11e9-8138-c9b5152e8e7e.png)
