### ISSUE TITLE
drop_na_columns does not work for data.table

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics#103]
Current implementation of `drop_na_columns` (after merging PR #100) is as follows:

```R
function(df){
  if (nrow(df) > 0) {
    # http://stackoverflow.com/questions/2643939/remove-columns-from-dataframe-where-all-values-are-na
    # Test more efficient call...
    # base::Filter(function(x) 
    #         !all(is.na(x)),
    #        df)
    df[,colSums(is.na(df))<nrow(df)]
  } else {
    df
  }
}
```

This works OK when the argument is a `data.frame`:
```R
revealgenomics:::drop_na_columns(data.frame(x = c(1,2), y = NA, z = 33))
#   x  z
# 1 1 33
# 2 2 33
```

But does not work when the argument is a data.table
```R
revealgenomics:::drop_na_columns(data.table(x = c(1,2), y = NA, z = 33))
#   x     y     z 
# TRUE FALSE  TRUE 
```

@mmccorry Could you take a look at this.

**Comment by mmccorry** [comment]
@ksens 

We can probably solve this by checking the class of `df` and switching on the method used -- so the above for a `data.frame` and another method for `data.table`.  

NB., a `data.table` is of both class `data.table` AND `data.frame`

**Comment by mmccorry** [comment]
This seems to work:


```
drop_na_columns <- function(df){
  if (nrow(df) > 0) {
    if( "data.table" %in% class(df) ) {
      # Use a different method to remove NA columns if a data.table
      # http://stackoverflow.com/questions/2643939/remove-columns-from-dataframe-where-all-values-are-na
      base::Filter(function(x)
              !all(is.na(x)),
             df)
      
    } else {
      df[,colSums(is.na(df))<nrow(df)]
    }
  } else {
    df
  }
}



drop_na_columns(data.frame(x = c(1,2, NA), y = NA, z = 33, d = c(NA, NA, NA)))
# x  z
# 1  1 33
# 2  2 33
# 3 NA 33
But does not work when the argument is a data.table

drop_na_columns(data.table(x = c(1,2, NA), y = NA, z = 33, d = c(NA, NA, NA)))
# x  z
# 1:  1 33
# 2:  2 33
# 3: NA 33
```

**Comment by ksens** [comment]
@mmccorry 

I was thinking of a similar solution, but had left it to you in case you knew a some special syntax that worked for both `data.table` and `data.frame`. Anyway the proposed solution works, and passes all tests. 

I also added two simple `testthat` tests to check that `drop_na_columns` works for both types. See commit https://github.com/Paradigm4/revealgenomics/commit/a43206b38294edef641c7ccb943ca283790182a0

Merging this PR. Thanks for the prompt response.

**Comment by mmccorry** [comment]
> @mmccorry
> 
> I was thinking of a similar solution, but had left it to you in case you knew a some special syntax that worked for both `data.table` and `data.frame`. Anyway the proposed solution works, and passes all tests.
> 
> I also added two simple `testthat` tests to check that `drop_na_columns` works for both types. See commit [a43206b](https://github.com/Paradigm4/revealgenomics/commit/a43206b38294edef641c7ccb943ca283790182a0)
> 
> Merging PR #104. Thanks for the prompt response.

@ksens - I recall attempting to find a more elegant solution that would work efficiently with both classes.  Don't believe I was able to at the time.

One method would be to call `setDT(df)` before removing NA columns, the call `setDF(df)`.  But that is less clean and not sure that would really give any performance benefit.  I could be wrong though..
