### ISSUE TITLE
[Benchmarking] Next set of requests v2

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics#109]
@arko-bhattacharya 

As follow up to #96 

- [x] Make sure `object.size` of biosamples is marked in bytes or Kb, and not Mb (otherwise too many are marked as zero Mb). 
- [x] In the script `get_downloadTime...`, separate the functions into a separate functions file (say `functions_benchmarking.R`) that can be sourced in the script -- that way folks who use your script can quickly see the important parameters in the call to `repeat_runs` (code will be more readable)
- [x] In the script `get_downloadTime...`,  keep only the minimal documentation e.g. I am currently only using the parameters `Branch` and `write_to_file_fp`. For more documentation, folks would need to look into `functions_benchmarking.R`

**Comment by arko-bhattacharya** [comment]
Object size on plot can now be provided by the user.

**Comment by ksens** [comment]
Confirming that all the above requests are completed. Closing issue.
