### ISSUE TITLE
Need tests for conversion of data.frame to matrix

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics#111]
@arko-bhattacharya 

#99 lists four cases for data.frame to matrix conversion. Some tests need to be added in the `testhat` framework to cover these four cases. 

An example of the framework is at:
https://github.com/Paradigm4/revealgenomics/blob/master/tests/testthat/test00-helper-functions.R#L10

Could you take a look?

**Comment by arko-bhattacharya** [comment]
Completed above request. Please review.

**Comment by ksens** [comment]
Tests added successfully. Accordingly, the following line shows up in Travis logs:

```
✔ |  14       | test-convert-dataframe-to-matrix:  [1.9 s]
```

Closing issue.
