### ISSUE TITLE
Need capability to snapshot state of database and restore snapshot

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics#121]
`revealgenomics` API manages data loading / querying over a fixed list of arrays. In the context of data loading, there is a need of application level rollback e.g. `register_dataset()` does the following data inserts:

- upload mandatory fields into `DATASET` array
- upload flexible fields into `DATASET_INFO` array
- maintain ontology arrays (potentially)
- maintain search index arrays (potentially)

Currently, if inserts succeeds in the first `N` steps, but fails at the `N+1`-th, then the database needs to rollback to the original state. 

@mmccorry I know you have already covered major ground on this -- I am writing my notes here for our discussion.

**Comment by ksens** [comment]
@mmccorry 

You can now install latest version of `revealgenomics` package and run the following function to get the list of arrays maintained by the API:

```R
revealgenomics:::get_list_of_arrays()
# [1] "gh_public.METADATA_ATTRKEY"       "gh_public.PROJECT"                "gh_public.PROJECT_INFO"          
# [4] "gh_secure.DATASET"                "gh_secure.DATASET_INFO"           "gh_secure.INDIVIDUAL"            
# [7] "gh_secure.INDIVIDUAL_INFO"        "gh_secure.BIOSAMPLE"              "gh_secure.BIOSAMPLE_INFO"        
# [10] "gh_secure.EXPERIMENTSET"          "gh_secure.MEASUREMENTSET"         "gh_secure.MEASUREMENTSET_INFO"   
# [13] "gh_secure.MEASUREMENT"            "gh_secure.MEASUREMENT_INFO"       "gh_public.VARIANT_KEY"           
# [16] "gh_public.ONTOLOGY"               "gh_public.ONTOLOGY_INFO"          "gh_public.DEFINITION"            
# [19] "gh_public.DEFINITION_INFO"        "gh_public.CHROMOSOME_KEY"         "gh_public.ONTOLOGY_CATEGORY"     
# [22] "gh_public.METADATA_VALUE"         "gh_secure.ENTITY_FLEX_FIELDS"     "gh_public.FEATURESET"            
# [25] "gh_public.FEATURESET_INFO"        "gh_public.FEATURE"                "gh_public.FEATURE_INFO"          
# [28] "gh_public.FEATURE_SYNONYM"        "gh_public.GENE_SYMBOL"            "gh_secure.FEATURE_SUMMARY"       
# [31] "gh_public.REFERENCESET"           "gh_public.REFERENCESET_INFO"      "gh_public.EXOMIC_VARIANT"        
# [34] "gh_public_rw.GENELIST"            "gh_public_rw.GENELIST_GENE"       "gh_secure.RNAQUANTIFICATION"     
# [37] "gh_secure.VARIANT"                "gh_secure.FUSION"                 "gh_secure.PROTEOMICS"            
# [40] "gh_secure.COPYNUMBER_MAT"         "gh_secure.COPYNUMBER_MAT_STRING"  "gh_secure.COPYNUMBER_VARIANT"    
# [43] "gh_secure.CYTOMETRY_CYTOF"        "gh_secure.EXOMIC_VARIANT_CALL"    "gh_secure.MEASUREMENTDATA_CACHE" 
# [46] "gh_r_object_store.R_OBJECT_CACHE" "permissions.dataset_id" 
```

This is a pretty long list, and we might even find a few of the arrays missing at deployment B. I need to create those arrays using `init_db(entity)` (for the missing entities)

Note that the following arrays are currently not used in scRNAseq project.
```
# "gh_public.CHROMOSOME_KEY"  
# "gh_public.EXOMIC_VARIANT"        
# [34] "gh_public_rw.GENELIST"            "gh_public_rw.GENELIST_GENE"       
# [37] "gh_secure.VARIANT"                "gh_secure.FUSION"                 "gh_secure.PROTEOMICS"            
# [40] "gh_secure.COPYNUMBER_MAT"         "gh_secure.COPYNUMBER_MAT_STRING"  "gh_secure.COPYNUMBER_VARIANT"    
# [43] "gh_secure.CYTOMETRY_CYTOF"        "gh_secure.EXOMIC_VARIANT_CALL"    "gh_secure.MEASUREMENTDATA_CACHE" 
```

**Comment by mmccorry** [comment]
@ksens 

I have added snapshot methods to `revealsc` (in Paradigm4/revealgenomics-apps) per our previous discussion: https://github.com/Paradigm4/revealgenomics/commit/05d2840e32c050f9ddc071cb635f035dc843a4da

For the scRNAseq project, I am subsetting this list per your comment above, and the two additional arrays added as well (see below), but getting the versions for each array still takes some time (seconds).

It may be helpful to reduce the number of arrays to snapshot dependent on the entities we are going to modify.

``` r
array_names = revealgenomics:::get_list_of_arrays()
array_names = array_names[!(
  array_names %in% c(
    "gh_r_object_store.R_OBJECT_CACHE",
    "permissions.dataset_id",
    "gh_public.CHROMOSOME_KEY" ,
    "gh_public.EXOMIC_VARIANT",
    "gh_public_rw.GENELIST",
    "gh_public_rw.GENELIST_GENE",
    "gh_secure.VARIANT",
    "gh_secure.FUSION",
    "gh_secure.PROTEOMICS",
    "gh_secure.COPYNUMBER_MAT",
    "gh_secure.COPYNUMBER_MAT_STRING",
    "gh_secure.COPYNUMBER_VARIANT",
    "gh_secure.CYTOMETRY_CYTOF",
    "gh_secure.EXOMIC_VARIANT_CALL",
    "gh_secure.MEASUREMENTDATA_CACHE"
  )
)]
```

**Comment by ksens** [comment]
@mmccorry 

If I am not wrong, the branch https://github.com/Paradigm4/revealgenomics/tree/add_array_snapshots is deprecated right? 

The functionality delivered in this ticket seems to have been deployed to `revealsc` package using PR https://github.com/Paradigm4/revealgenomics-apps/pull/76.

If you agree, I would delete this branch from `revealgenomics` package.

**Comment by ksens** [comment]
Resolved via PR at `revealsc` repo https://github.com/Paradigm4/revealgenomics-apps/pull/76 (not targeted for this repo just now). 

Closing issue.
