### ISSUE TITLE
Framework to compare timings between two branches of this package

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics#92]
@arko-bhattacharya

Following up on our discussion to set up a framework to benchmark download timings between `master` and `data.table_optimizations`/`data.table_optimizations_v2` (or for that matter, any other test branch in the future):

The following script shows how to download and time downloads for all expression pipelines on a server where revealgenomics API is deployed. The script prints all outputs to R console. I envision:
- collecting all the timings (biosample, expression etc.) into some kind of data structure (a TSV file, an R data structure stored as an .RDS object etc.). 
- Then another script would be used to compare the data structure collected between two runs (one run on `master` and one run on the test branch). This script should then spit out some statistics about % degradation/improvement, and potentially a graph comparing the performance between two branches. 

```R
rm(list=ls())
library(revealgenomics)
if (file.exists('~/.scidb_secure_user_auth')) {
  creds_file = '~/.rg_config_secure-ro.json'
  rg_connect(username = read_json(creds_file)$`user-name`, password = read_json(creds_file)$`user-password`) 
} else {
  rg_connect(username = Sys.getenv("LOGNAME")) # will prompt for password
}

####  1. get all the datasets #### 
d = get_datasets()
d$name
# [1] "placeholder_public_dataset" "TCGA-LAML"                  "TCGA-ACC"                  
# [4] "TCGA-BLCA"                  "TCGA-LGG"                   "TCGA-BRCA"                 
# ....
# [34] "TCGA-UCEC"                  "TCGA-UVM"                   "ARCHS4 human"              
# [37] "malt_10k_protein_v3"        "pbmc_10k_v3"                "neuron_10k_v3"             
# [40] "heart_10k_v3"               "pbmc8k"                     "neuron_9k"                 
# [43] "nuclei_2k"                  "TestSearchByValsDataset2"   "TestSearchByValsDataset1" 

#### Note
# No expression data in
# - `placeholder_public_dataset`
# - `TestSearchByValsDataset[x]`
# Focus on 
# - TCGA datasets (these are regular gene expression datasets)
# - malt_10k... to pbmc8k (these are single cell gene expression datasets)
# In terms of benchmarking, we have to ignore
# - ARCHS4 (this has one matrix with several 100 GB -- we do not envision downloading this in one go)


#### 2. get information about all the pipelines #### 
ms = get_measurementsets()
table(ms$entity)
# RNAQUANTIFICATION 
# 112

table(ms$name)
# Expression (gene level) Expression (transcript level)                HTSeq - Counts 
#                       1                             1                            34 
# HTSeq - FPKM               HTSeq - FPKM-UQ                        normal 
#           34                            34                             7 
# TPM (transcript level) 
#                     1 


#### 3. Now run a loop and time download for expression data in each pipeline #### 
for (idx in 1:nrow(ms)) {
  msi = drop_na_columns(ms[idx, ])
  d_sel = drop_na_columns(d[d$dataset_id == msi$dataset_id, ])
  message("Working on:\n", 
          "\tdataset_id: ", msi$dataset_id, ", dataset_name: ", d_sel$name, 
          "\n\tmeasurementset_id: ", msi$measurementset_id, ", measurementset_name: ", msi$name)
  
  t1 = proc.time()
  bios_ref = search_biosamples(dataset_id = msi$dataset_id)
  dt1 = (proc.time()-t1)[3]
  message("Time taken to download biosamples: ", as.numeric(dt1))
  
  # Putting this in a try catch as some downloads (like for ARCHS4) will fail
  try({
    t1 = proc.time()
    res1 = search_expression(measurementset = msi, biosample_ref = bios_ref)
    dt2 = (proc.time()-t1)[3]
    message("Time taken to download expression data, features from scidb and formulate ExpressionSet object: ", as.numeric(dt2))
  })
  
}
```

**Comment by ksens** [comment]
First prototype deployed by @arko-bhattacharya via #95. Closing issue -- will open new feature requests on this topic as needed.

**Comment by arko-bhattacharya** [comment]
Results of the first prototype can be viewed at - http://34.238.117.109:8787/files/benchmarking_plots/benchmarking_plot_20180911.html
OR
http://34.238.117.109:8787/files/benchmarking_plots/benchmarking_plot_20180910.html

From these graphs we can see that for data-sets of small size (less than 100Mb) both the branches i.e. master and data.table_enhancements_v2 perform similarly however data.table_enhancements_v2's performance seems to increase significantly as the size of data-sets increase (greater than 100Mb).

**Comment by ksens** [comment]
Thanks @arko-bhattacharya. When I visit the URL, it says no files found. Maybe because they are visible to your user but not to mine. 

Can you try attaching the HTML files to this ticket? 

Keeping the ticket open to track such items.

**Comment by arko-bhattacharya** [comment]
PFA images of the above interactive plots - 

- benchmarking_plot_20180911.html
![runTime_20190811](https://user-images.githubusercontent.com/16749721/62881369-4c323100-bd4d-11e9-85af-25b109504e16.png)

- benchmarking_plot_20180910.html
![runTime_20190810](https://user-images.githubusercontent.com/16749721/62881709-ff9b2580-bd4d-11e9-8a60-754c92472c1e.png)


Will upload HTML files soon.

**Comment by ksens** [comment]
@arko-bhattacharya 

Perfect. Clearly shows that `data.table enhancements` branch performs better than `master`. Also thanks for adding the line plot for download size. 

Nit: Could you change the code so that the line plot to be of a different color than blue or green that are being used for the box plots. Do not need to re-upload images. Just make the change in the code and push that commit. 

PS: We can figure out the HTML upload when we meet next. For the data above, the attached images are sufficiently informative.

**Comment by ksens** [comment]
@arko-bhattacharya 

A few more requests on this:

1. Can you paste in the corresponding graphs for downloading biosamples (using Kb as the unit size)?
2. Can you rerun the script with download for individuals (using `search_individuals` instead of `search_biosamples`). In the script, also turn off expression download (maybe put in some NA results as placeholders) so that the `get_time...` script runs faster.

**Comment by ksens** [comment]
This ticket is superseded by #96 and #102. Closing.

**Comment by arko-bhattacharya** [comment]
Benchmarking plot for search_expression (size in Mb) -
![runTime-20190903-search_expression](https://user-images.githubusercontent.com/16749721/64192088-8d72b800-ce97-11e9-985e-c24fee53e5ec.png)

Benchmarking plot for search_biosample (size in Kb) -
![runTime-20190903-search_biosamples](https://user-images.githubusercontent.com/16749721/64192127-a3807880-ce97-11e9-8ffb-8a15e841d7fc.png)

**Comment by ksens** [comment]
Awesome, thanks! Archiving some of these at https://github.com/Paradigm4/revealgenomics/wiki/Benchmark-results for easy access.
