### ISSUE TITLE
[Benchmarking] Next set of requests

### ISSUE THREAD

**Issue by ksens** [Paradigm4/revealgenomics#96]
@arko-bhattacharya 

Was able to run your benchmarking scripts on customer A (with minor modifications), and to plot trends. 

Observations:
- `data.table_enhancements` branch suggested by @mmccorry is faster in almost all cases. 
- The improvement is not as high as expected in some cases (this is probably because of some corner cases where the improvements in the branch cannot be utilized; more on that when we meet next)

Am listing some feature requests relating to benchmarking scripts:

1. [x] Include run number in `data/log_raw/runTime_20190730.txt` e.g. `run 3 of N`
2. [x] At the end of every run, dump the stats into the .csv file (this way, if I have completed say 4 of 6 runs, I can start doing some analyis while the `get_time..` script keeps running in the background). 
	+ This is important because getting download times is the long pole in the analysis e.g. at customer A, getting 6 runs of expression data timings across all RNA-seq pipelines took ~9 hours
3. [x] To the final plotly plot, add a line plot marking the expression-set size in Mb. We will need a separate y-axis for this (i.e. a second detached y-axis to the right)

**PS**: Just for our future reference, here is my command to run the `get_time..` script in the background. Allows me to run analysis on RStudio. 

```R
# In Unix, open a terminal in a screen
# Then run the script
R --slave -e "source('/path/to/get_downloadTime_data.R')"
```

**Comment by arko-bhattacharya** [comment]
Added a separate Y-axis for size in Mb.

**Comment by arko-bhattacharya** [comment]
Added run number to log files and updated get_downloadTime_data.R to write into .csv file at the end of each run.

**Comment by ksens** [comment]
Assigning to myself for testing.

**Comment by ksens** [comment]
@arko-bhattacharya 

Minor -- the run number (e.g. `3 of N`) is still not coming in `log_raw/runTime...`. Here is what I get from latest commit at #108 

```
branch:dte_v4|ds_name:Olschwang Colorectal (GSE37892)|ds_id :26|ms_name:justRMA 1.0.0: Affymetrix Bioconductor CDF v3.2.0: hgu133plus2cdf|ms_id:79
search_biosamples() -
time (Sec): 0.164000000000044
size (Mb): 0.1 Mb
search_expression() -
Downloading full dataset from SciDB ... done (4.175 sec)
Downloading features to form ExpressionSet ... done (1.335 sec)
Forming ExpressionSet ... Reshaping expr to Matrix ... Handling discontinuous dense matrix case ... done (0.397 sec)
time (sec): 7.39500000000004
size (Mb): 44.6 Mb
```

**Comment by ksens** [comment]
@arko-bhattacharya 

As seen at https://github.com/Paradigm4/revealgenomics/pull/108#issuecomment-527371263, the line plot for expression data size (with separate y-axis) is still not showing up. 

Could you check the code for plotly plotting at https://github.com/Paradigm4/revealgenomics/blob/master/scripts/3-run-time-comparison-between-branches/plot_runTime_data.R to make sure it has your version of the code that plots this data.

**Comment by arko-bhattacharya** [comment]
Pushed changes from local. Due to these commits -
1. benchmarking scripts return run number
2. write outputs after every run
3. allow user to specify the desired unit of object size (Kb / Mb) on benchmarking plot.
4. render benchmarking plot with a second Y-axis to indicate object size.

**Comment by ksens** [comment]
Closing issue as all requests seem to have been covered.
